// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions (including VB)

#include <stdio.h>
#include <string.h>

#include "Define.h"

#include "united.h"

#include "unitedgm.h"
#include "unitedvw.h"
